updated initd and created defaults

diff --git a/initd b/initd
--- a/initd
+++ b/initd
@@ -1,5 +1,15 @@
 #! /bin/sh
 
+# Copyright (C) 2011- by Mar2zz <LaSi.Mar2zz@gmail.com>
+# released under GPL, version 2 or later
+
+
+################################################
+#                                              #
+#  TO CONFIGURE EDIT /etc/default/maraschino
+#                                              #
+################################################
+
 ### BEGIN INIT INFO
 # Provides:          Maraschino application instance
 # Required-Start:    $all
@@ -10,50 +20,122 @@
 # Description:       starts instance of Maraschino using start-stop-daemon
 ### END INIT INFO
 
-############### EDIT ME ##################
-# path to app
-APP_PATH=/path/to/maraschino
 
-# path to python bin
+# main variables
 DAEMON=/usr/bin/python
+SETTINGS=/etc/default/maraschino
 
-# startup args
-DAEMON_OPTS=" maraschino-cherrypy.py -q"
+SETTINGS_LOADED=FALSE
 
-# script name
-NAME=maraschino
-
-# app name
 DESC=Maraschino
 
-# user
-RUN_AS=root
+# only accept values from /etc/default/maraschino
+unset RUN_AS CONFIG DATADIR PID_FILE
 
-PID_FILE=/var/run/maraschino.pid
+. /lib/lsb/init-functions
 
-############### END EDIT ME ##################
+[ -x $DAEMON ] || {
+    log_warning_msg "$DESC: Can't execute daemon, aborting. See $DAEMON";
+    return 1; }
 
-test -x $DAEMON || exit 0
+[ -r $SETTINGS ] || {
+    log_warning_msg "$DESC: Can't read settings, aborting. See $SETTINGS";
+    return 1; }
 
-set -e
+check_retval() {
+    if [ $? -eq 0 ]; then
+        log_end_msg 0
+        return 0
+    else
+        log_end_msg 1
+        exit 1
+    fi
+}
+
+load_settings() {
+    if [ $SETTINGS_LOADED != "TRUE" ]; then
+        . $SETTINGS
+
+        [ -n "$APP_PATH" ] || {
+            log_warning_msg "$DESC: path to $DESC not set, aborting. See $SETTINGS";
+            return 1; }
+
+        [ $ENABLE_DAEMON != 1 ] && {
+            log_warning_msg "$DESC: daemon not enabled, aborting. See $SETTINGS";
+            return 1; }
+
+        [ -z "$RUN_AS" ] && {
+            log_warning_msg "$DESC: daemon username not set, aborting. See $SETTINGS";
+            return 1; }
+        [ -z "${RUN_AS%:*}" ] && exit 1
+
+        DAEMON_OPTS="Maraschino.py"
+
+        [ -n "$PID_FILE" ] && PID_FILE=$PID_FILE
+        [ -n "$PID_FILE" ] || PID_FILE=/var/run/maraschino/maraschino.pid
+
+        SETTINGS_LOADED=TRUE
+    fi
+    return 0
+}
+
+load_settings || exit 0
+
+is_running () {
+    # returns 1 when running, else 0.
+    PID=$(pgrep -f "$DAEMON_OPTS")
+    RET=$?
+    [ $RET -gt 1 ] && exit 1 || return $RET
+}
+
+handle_pid () {
+    PID_PATH=`dirname $PID_FILE`
+    [ -d $PID_PATH ] || mkdir -p $PID_PATH && chown -R $RUN_AS $PID_PATH > /dev/null || {
+        log_warning_msg "$DESC: Could not create $PID_FILE, aborting.";
+        return 1;}
+}
+
+enable_updates () {
+    chown -R $RUN_AS $APP_PATH > /dev/null || {
+        log_warning_msg "$DESC: $APP_PATH not writable for web-updates, See $SETTINGS";
+        return 0; }
+}
+
+start_maraschino () {
+    if ! is_running; then
+        log_daemon_msg "Starting $DESC"
+        [ "$WEB_UPDATE" = 1 ] && enable_updates
+        handle_pid
+        start-stop-daemon -o -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
+        check_retval
+    else
+        log_success_msg "$DESC: already running (pid $PID)"
+    fi
+}
+
+stop_maraschino () {
+    if is_running; then
+        log_daemon_msg "Stopping $DESC"
+        start-stop-daemon -o --stop --pidfile $PID_FILE --retry 15
+        check_retval
+    else
+        log_success_msg "$DESC: not running"
+    fi
+}
+
 
 case "$1" in
-  start)
-        echo "Starting $DESC"
-        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
+    start)
+        start_maraschino
         ;;
-  stop)
-        echo "Stopping $DESC"
-        start-stop-daemon --stop --pidfile $PID_FILE
+    stop)
+        stop_maraschino
         ;;
-
-  restart|force-reload)
-        echo "Restarting $DESC"
-        start-stop-daemon --stop --pidfile $PID_FILE
-        sleep 15
-        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
+    restart|force-reload)
+        stop_maraschino
+        start_maraschino
         ;;
-  *)
+    *)
         N=/etc/init.d/$NAME
         echo "Usage: $N {start|stop|restart|force-reload}" >&2
         exit 1
